/** FlatOutOverview.tsx — main composition.
 *
 *  9 scenes timed against the Kokoro narration manifest. Each scene reads its
 *  duration from public/audio/manifest.json (generated by scripts/generate-narration.mjs)
 *  + plays its own .wav via <Audio>. Subtitles are burned in scene-by-scene from
 *  the same manifest so re-running the narration script auto-updates everything.
 *
 *  Total runtime ≈ 105s + 5s of inter-scene padding ≈ 110s @ 30fps = 3300 frames.
 *
 *  Why one big file instead of one per scene: each scene is short (5-15s) and the
 *  visual logic is a flat list of <Sequence> children. Splitting would force an
 *  index file to re-export them and add boilerplate without payoff. The brand
 *  tokens + chrome primitives DO live in their own modules (brand.ts + components.tsx)
 *  so the per-scene markup stays focussed on motion + composition.  */

import React from 'react';
import { AbsoluteFill, Audio, Sequence, staticFile, useCurrentFrame, useVideoConfig, Easing, interpolate } from 'remotion';
import { loadFont as loadOswald } from '@remotion/google-fonts/Oswald';
import { loadFont as loadRubik } from '@remotion/google-fonts/Rubik';
import { loadFont as loadJetBrains } from '@remotion/google-fonts/JetBrainsMono';
import manifest from '../public/audio/manifest.json';
import { COLOR, FONT, BLADE_CLIP } from './brand';
import { Backdrop, BladeMark, Wordmark, PanelFrame, TerminalFrame, Speedo, Subtitle, SceneLabel, e } from './components';

/* Load brand fonts — Remotion's Google Fonts integration handles the @font-face
 * + waitFor logic automatically so the renderer doesn't snapshot frames before
 * the typeface is ready. */
loadOswald();
loadRubik();
loadJetBrains();

/* ────────── TIMELINE ──────────
 *  Each scene gets its narration's frame count + a small `pad` of breathing
 *  room before the next scene so the cuts don't feel mechanical. Total =
 *  Σ(narration + pad). Scenes resolve their start/end at render time from
 *  the cumulative offsets so re-recording one scene auto-shifts the rest. */
type SceneId = 'title' | 'hook' | 'voice' | 'vision' | 'edit' | 'brand' | 'memory' | 'install' | 'outro';
const PAD_FRAMES = 18;            /* 0.6s breathing room between scenes */
const PAD_FIRST = 12;             /* tighter pad on the title — viewer wants the hook fast */
const PAD_OUTRO = 60;             /* hold on the outro for 2s after narration so the brand mark lingers */

interface SceneInfo { id: SceneId; text: string; file: string | null; seconds: number; frames: number; }

const scenes: SceneInfo[] = manifest as SceneInfo[];

/** Compute scene timing (start, duration, end) including per-scene pads. The
 *  exported getTotalFrames() reads this so Root.tsx knows the composition length. */
function buildTimeline() {
  const out: { id: SceneId; start: number; duration: number; pad: number; text: string; file: string | null }[] = [];
  let cursor = 0;
  scenes.forEach((s, i) => {
    const pad = i === 0 ? PAD_FIRST : i === scenes.length - 1 ? PAD_OUTRO : PAD_FRAMES;
    const duration = s.frames + pad;
    out.push({ id: s.id, start: cursor, duration, pad, text: s.text, file: s.file });
    cursor += duration;
  });
  return out;
}
const timeline = buildTimeline();
export function getTotalFrames() {
  return timeline.reduce((a, t) => a + t.duration, 0) || 3300;
}

/* ────────── MAIN COMPOSITION ────────── */
export const FlatOutOverview: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: COLOR.ink0 }}>
      <Backdrop />
      {timeline.map((scene) => (
        <Sequence key={scene.id} from={scene.start} durationInFrames={scene.duration}>
          <SceneRouter id={scene.id} text={scene.text} file={scene.file} duration={scene.duration} />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};

/* ────────── SCENE ROUTER ──────────
 *  Plays the narration audio + bottom subtitle for every scene, then dispatches
 *  to a per-scene visual. Keeping audio + subtitle logic in one place means a
 *  scene component only worries about its hero visual. */
const SceneRouter: React.FC<{ id: SceneId; text: string; file: string | null; duration: number }> = ({ id, text, file, duration }) => {
  const Visual = SCENE_COMPONENTS[id];
  return (
    <AbsoluteFill>
      {file && <Audio src={staticFile(file)} />}
      <Visual duration={duration} />
      <Subtitle text={text} />
    </AbsoluteFill>
  );
};

/* ────────── SCENE 1 · TITLE (3.75s) ──────────
 *  FOM blade mark fades in centre, then the wordmark resolves below it. Brand
 *  red bloom from the blade radiates outward. */
const TitleScene: React.FC<{ duration: number }> = () => {
  const f = useCurrentFrame();
  const bladeOpacity = e(f, [0, 18], [0, 1]);
  const bladeScale   = e(f, [0, 30], [0.6, 1.0]);
  const wordmarkOpacity = e(f, [16, 40], [0, 1]);
  const wordmarkY = e(f, [16, 40], [20, 0]);
  return (
    <AbsoluteFill style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', gap: 36 }}>
      <div style={{ opacity: bladeOpacity, transform: `scale(${bladeScale})` }}>
        <BladeMark size={180} />
      </div>
      <div style={{ opacity: wordmarkOpacity, transform: `translateY(${wordmarkY}px)` }}>
        <Wordmark scale={1.3} tagline />
      </div>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 2 · HOOK (12.27s) ──────────
 *  Speedometer needle sweeps idle → listening → thinking → speaking, with state
 *  labels appearing in time with the narration's "listens, sees, edits, remembers".
 *  Capability tiles fade in to the right of the speedo so the viewer sees the
 *  product surface, not just an abstraction. */
const HookScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  /* Needle sweeps 5 → 60 → 140 → 90 → 30 over the scene — corresponds to idle,
   * listening, thinking, speaking, idle. Labels animate in step. */
  const needle = (() => {
    if (f < 60)   return e(f, [0, 60], [5, 60]);
    if (f < 150)  return e(f, [60, 150], [60, 140]);
    if (f < 240)  return e(f, [150, 240], [140, 90]);
    return e(f, [240, duration], [90, 30]);
  })();
  const states = [
    { label: 'LISTENS', from: 60,  to: 150 },
    { label: 'SEES',    from: 150, to: 240 },
    { label: 'EDITS',   from: 240, to: 330 },
    { label: 'REMEMBERS', from: 330, to: duration },
  ];
  const speedoOpacity = e(f, [0, 24], [0, 1]);
  return (
    <AbsoluteFill style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-evenly' }}>
      <div style={{ opacity: speedoOpacity }}>
        <Speedo size={420} needle={needle} state={states.find(s => f >= s.from && f < s.to)?.label || 'STANDBY'} />
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 18, width: 420 }}>
        {states.map((s, i) => {
          const opacity = e(f, [s.from, s.from + 18], [0, 1]);
          const x = e(f, [s.from, s.from + 18], [40, 0]);
          return (
            <div key={s.label} style={{
              opacity, transform: `translateX(${x}px)`,
              padding: '16px 22px',
              background: COLOR.ink1,
              border: `1px solid ${COLOR.red}`,
              clipPath: BLADE_CLIP,
              fontFamily: FONT.display,
              fontWeight: 700,
              fontSize: 32,
              letterSpacing: '0.15em',
              color: COLOR.text,
              textTransform: 'uppercase',
              boxShadow: `0 0 18px ${COLOR.redGlow}`,
            }}>{s.label}</div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 3 · VOICE (14.61s) ──────────
 *  Operator's transcript bubble appears, then the assistant's reply types in
 *  below. Mic waveform + speedometer in "speaking" state on the right. */
const VoiceScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  const heardOpacity = e(f, [12, 36], [0, 1]);
  /* Heard text types in over ~2s starting at frame 30. */
  const heardText = "Hey Flat-Out, cut a 30-second teaser of yesterday's Aston shoot.";
  const heardChars = Math.min(heardText.length, Math.floor(e(f, [30, 90], [0, heardText.length])));
  const replyStart = 100;
  const replyText = "On it. Rendering the Aston teaser — about three minutes.";
  const replyChars = Math.min(replyText.length, Math.floor(e(f, [replyStart, replyStart + 70], [0, replyText.length])));
  const replyOpacity = e(f, [replyStart - 6, replyStart + 12], [0, 1]);
  /* Speaking-real waveform: synthetic amp pulse from frame 170 onward. */
  const wfActive = f > 170;
  return (
    <AbsoluteFill style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-evenly', padding: '0 80px' }}>
      <SceneLabel chapter="01 · VOICE LOOP" title="Hands-free editing" opacity={e(f, [0, 18], [0, 1])} />

      <div style={{ display: 'flex', flexDirection: 'column', gap: 28, width: 760 }}>
        {/* Heard bubble */}
        <div style={{ opacity: heardOpacity }}>
          <div style={{ fontFamily: FONT.display, fontSize: 12, letterSpacing: '0.4em', color: COLOR.green, marginBottom: 8 }}>HEARD</div>
          <div style={{
            padding: '20px 28px',
            background: COLOR.ink1,
            border: `1px solid ${COLOR.green}`,
            clipPath: BLADE_CLIP,
            fontFamily: FONT.body,
            fontSize: 26,
            color: COLOR.text,
            lineHeight: 1.4,
          }}>{heardText.slice(0, heardChars)}<span style={{ color: COLOR.green }}>{heardChars < heardText.length ? '▍' : ''}</span></div>
        </div>

        {/* Reply bubble */}
        <div style={{ opacity: replyOpacity }}>
          <div style={{ fontFamily: FONT.display, fontSize: 12, letterSpacing: '0.4em', color: COLOR.red, marginBottom: 8 }}>FLAT-OUT</div>
          <div style={{
            padding: '20px 28px',
            background: COLOR.ink1,
            border: `1px solid ${COLOR.red}`,
            clipPath: BLADE_CLIP,
            fontFamily: FONT.body,
            fontSize: 26,
            color: COLOR.text,
            lineHeight: 1.4,
            boxShadow: `0 0 22px ${COLOR.redGlow}`,
          }}>{replyText.slice(0, replyChars)}<span style={{ color: COLOR.red }}>{replyChars < replyText.length ? '▍' : ''}</span></div>
        </div>
      </div>

      {/* Speedo in speaking state on the right */}
      <div>
        <Speedo size={320} needle={wfActive ? 100 + Math.sin(f * 0.3) * 25 : 30} state={wfActive ? "SPEAKING" : "LISTENING"} />
      </div>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 4 · VISION (10.22s) ──────────
 *  Grid of 6 thumbnails with captions appearing under each as the scene plays.
 *  Highlights "front-grille hero" with a red border + glow when the narrator
 *  says it. */
const VisionScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  /* 6 stylised car thumbnails — pure CSS gradients evoking different angles. */
  const thumbs = [
    { label: '3/4 FRONT',    captionAt: 30,  caption: 'Aston Vulcan, 3/4 front, golden hour, low angle.' },
    { label: 'FRONT GRILLE', captionAt: 60,  caption: 'Front grille, centre framing, deep shadow detail.', hero: true },
    { label: 'PROFILE',      captionAt: 90,  caption: 'Profile, mid-stroke, late afternoon backlight.' },
    { label: 'REAR 3/4',     captionAt: 120, caption: 'Rear 3/4, racing line, wet tarmac reflection.' },
    { label: 'INTERIOR',     captionAt: 150, caption: 'Interior, driver POV, carbon trim, red stitch.' },
    { label: 'DETAIL',       captionAt: 180, caption: 'Engine bay, V12 detail, branding visible.' },
  ];
  const labelOpacity = e(f, [0, 18], [0, 1]);
  const heroPulse = f > 60 ? 0.6 + Math.sin((f - 60) * 0.2) * 0.4 : 0;
  return (
    <AbsoluteFill style={{ padding: '160px 80px 120px' }}>
      <SceneLabel chapter="02 · VISION" title="Sees every shot" opacity={labelOpacity} />
      <div style={{
        marginTop: 110,
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: 24,
      }}>
        {thumbs.map((t, i) => {
          const opacity = e(f, [i * 12, i * 12 + 24], [0, 1]);
          const captionOpacity = e(f, [t.captionAt, t.captionAt + 18], [0, 1]);
          return (
            <div key={t.label} style={{ opacity, display: 'flex', flexDirection: 'column', gap: 8 }}>
              <div style={{
                aspectRatio: '16 / 9',
                background: `linear-gradient(135deg, ${COLOR.ink2} 0%, ${COLOR.ink0} 100%)`,
                border: `1px solid ${t.hero ? COLOR.red : COLOR.line}`,
                clipPath: BLADE_CLIP,
                position: 'relative',
                overflow: 'hidden',
                boxShadow: t.hero ? `0 0 ${24 * heroPulse}px ${COLOR.redGlow}` : 'none',
              }}>
                {/* Stylised "car silhouette" — a rotated red highlight bar to evoke a hero shape */}
                <div style={{
                  position: 'absolute', top: '40%', left: '15%', right: '15%', height: '20%',
                  background: `linear-gradient(90deg, ${COLOR.red} 0%, transparent 100%)`,
                  opacity: 0.3, transform: 'skewX(-20deg)',
                }} />
                {/* Bracket markers in corners */}
                {['tl', 'tr', 'bl', 'br'].map(p => (
                  <span key={p} style={{
                    position: 'absolute',
                    width: 14, height: 14,
                    border: `2px solid ${t.hero ? COLOR.red : COLOR.text}`,
                    borderTopWidth: p.startsWith('t') ? 2 : 0,
                    borderBottomWidth: p.startsWith('b') ? 2 : 0,
                    borderLeftWidth: p.endsWith('l') ? 2 : 0,
                    borderRightWidth: p.endsWith('r') ? 2 : 0,
                    top: p.startsWith('t') ? 8 : undefined,
                    bottom: p.startsWith('b') ? 8 : undefined,
                    left: p.endsWith('l') ? 8 : undefined,
                    right: p.endsWith('r') ? 8 : undefined,
                    opacity: 0.7,
                  }} />
                ))}
                <div style={{
                  position: 'absolute', top: 12, left: 14,
                  fontFamily: FONT.display, fontSize: 11, letterSpacing: '0.3em',
                  color: t.hero ? COLOR.red : COLOR.textDim,
                }}>{t.label}{t.hero ? ' · HERO' : ''}</div>
              </div>
              <div style={{
                opacity: captionOpacity,
                fontFamily: FONT.body, fontSize: 14, color: COLOR.textDim, lineHeight: 1.4,
              }}>{t.caption}</div>
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 5 · EDIT PIPELINE (11.88s) ──────────
 *  Pipeline lanes with progress bars: SCAN → PLAN → ENCODE → CONCAT → FINAL. */
const EditScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  const stages = [
    { label: 'SCAN SHOOT',     start: 30,  end: 80,  done: 90 },
    { label: 'PLAN CUTS',      start: 80,  end: 130, done: 140 },
    { label: 'ENCODE',         start: 130, end: 220, done: 230 },
    { label: 'BEAT-SYNC MUSIC', start: 220, end: 270, done: 280 },
    { label: 'CONCAT + OUTRO', start: 270, end: 310, done: 320 },
    { label: 'FINAL.MP4',      start: 310, end: 340, done: 350 },
  ];
  return (
    <AbsoluteFill style={{ padding: '160px 80px 120px' }}>
      <SceneLabel chapter="03 · CINEMATIC EDITS" title="Voice → MP4 in 3 minutes" opacity={e(f, [0, 18], [0, 1])} />
      <div style={{ marginTop: 100, display: 'flex', flexDirection: 'column', gap: 14 }}>
        {stages.map((s, i) => {
          const pct = f < s.start ? 0 : f >= s.end ? 100 : ((f - s.start) / (s.end - s.start)) * 100;
          const opacity = e(f, [i * 6, i * 6 + 24], [0, 1]);
          const isDone = f >= s.done;
          return (
            <div key={s.label} style={{
              opacity,
              display: 'grid',
              gridTemplateColumns: '260px 1fr 80px',
              gap: 16,
              alignItems: 'center',
              padding: '14px 22px',
              background: COLOR.ink1,
              border: `1px solid ${isDone ? COLOR.green : COLOR.line}`,
              clipPath: BLADE_CLIP,
            }}>
              <span style={{
                fontFamily: FONT.display, fontSize: 18, letterSpacing: '0.2em',
                color: isDone ? COLOR.green : COLOR.text,
              }}>{s.label}</span>
              <div style={{
                height: 8, background: COLOR.ink2, position: 'relative', overflow: 'hidden',
              }}>
                <div style={{
                  width: `${pct}%`, height: '100%',
                  background: isDone ? COLOR.green : `linear-gradient(90deg, ${COLOR.redDeep} 0%, ${COLOR.red} 100%)`,
                  boxShadow: isDone ? 'none' : `0 0 12px ${COLOR.redGlow}`,
                  transition: 'width 0.1s',
                }} />
              </div>
              <span style={{
                fontFamily: FONT.mono, fontSize: 18, color: isDone ? COLOR.green : COLOR.textDim, textAlign: 'right',
              }}>{isDone ? '✓' : `${pct.toFixed(0)}%`}</span>
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 6 · BRAND PACK + LIVE SHOOT (14.42s) ──────────
 *  Left half: 4 aspect ratio crops morphing in. Right half: phone mock with
 *  "FLAG HERO" tap. */
const BrandScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  const aspects = [
    { label: '16:9',  w: 240, h: 135, at: 30  },
    { label: '9:16',  w: 90,  h: 160, at: 60  },
    { label: '1:1',   w: 160, h: 160, at: 90  },
    { label: '4:5',   w: 120, h: 150, at: 120 },
  ];
  return (
    <AbsoluteFill style={{ padding: '160px 80px 120px', display: 'flex', gap: 60 }}>
      <SceneLabel chapter="04 · DELIVERABLES" title="One command, every aspect" opacity={e(f, [0, 18], [0, 1])} />

      {/* LEFT: aspect grid */}
      <div style={{ flex: 1, marginTop: 100, display: 'flex', flexDirection: 'column', gap: 24, alignItems: 'flex-start' }}>
        <div style={{
          fontFamily: FONT.display, fontSize: 16, letterSpacing: '0.3em', color: COLOR.red, opacity: e(f, [0, 18], [0, 1]),
        }}>BRAND PACK · 4 ASPECTS</div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 28, alignItems: 'flex-end' }}>
          {aspects.map(a => {
            const opacity = e(f, [a.at, a.at + 24], [0, 1]);
            const scale = e(f, [a.at, a.at + 36], [0.5, 1.0]);
            return (
              <div key={a.label} style={{ opacity, transform: `scale(${scale})`, transformOrigin: 'bottom center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10 }}>
                <div style={{
                  width: a.w, height: a.h,
                  background: `linear-gradient(135deg, ${COLOR.ink2}, ${COLOR.ink0})`,
                  border: `1px solid ${COLOR.red}`,
                  clipPath: BLADE_CLIP,
                  position: 'relative',
                  overflow: 'hidden',
                }}>
                  {/* Stylised hero highlight */}
                  <div style={{
                    position: 'absolute', top: '30%', left: '10%', right: '10%', height: '40%',
                    background: `linear-gradient(45deg, transparent 0%, ${COLOR.red} 50%, transparent 100%)`,
                    opacity: 0.4,
                  }} />
                  {/* Watermark stamp */}
                  <div style={{
                    position: 'absolute', bottom: 6, right: 8,
                    fontFamily: FONT.display, fontSize: 8, letterSpacing: '0.2em', color: COLOR.text, opacity: 0.7,
                  }}>FOM</div>
                </div>
                <div style={{
                  fontFamily: FONT.display, fontSize: 14, letterSpacing: '0.3em', color: COLOR.textDim,
                }}>{a.label}</div>
              </div>
            );
          })}
        </div>
        <div style={{
          marginTop: 8, fontFamily: FONT.mono, fontSize: 14, color: COLOR.textDim,
          opacity: e(f, [150, 180], [0, 1]),
        }}>+ clean variants · + credit.txt · zipped for client</div>
      </div>

      {/* RIGHT: phone mock with flag tap */}
      <div style={{ width: 360, marginTop: 100, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 24 }}>
        <div style={{
          fontFamily: FONT.display, fontSize: 16, letterSpacing: '0.3em', color: COLOR.red, opacity: e(f, [240, 270], [0, 1]),
        }}>LIVE SHOOT MODE</div>
        <div style={{
          width: 240, height: 480,
          background: COLOR.ink0,
          borderRadius: 36,
          border: `8px solid #2a2a2c`,
          padding: 14,
          opacity: e(f, [240, 270], [0, 1]),
          transform: `translateY(${e(f, [240, 280], [40, 0])}px)`,
        }}>
          <div style={{
            width: '100%', height: '100%', background: COLOR.ink1, borderRadius: 22, padding: 16,
            display: 'flex', flexDirection: 'column', justifyContent: 'space-between',
          }}>
            <div>
              <div style={{ fontFamily: FONT.display, fontSize: 12, letterSpacing: '0.2em', color: COLOR.red }}>FLAT-OUT LIVE</div>
              <div style={{ fontFamily: FONT.mono, fontSize: 9, color: COLOR.green, marginTop: 4 }}>● connected</div>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 6 }}>
              {['HERO', 'KEEP', 'MAYBE', 'RESHOOT'].map((b, i) => {
                const isHero = b === 'HERO';
                const pulseFrame = 320;
                const isPulsing = isHero && f > pulseFrame && f < pulseFrame + 30;
                return (
                  <div key={b} style={{
                    padding: '10px 4px',
                    background: isPulsing ? COLOR.red : COLOR.ink2,
                    border: `1px solid ${isHero ? COLOR.red : COLOR.line}`,
                    fontFamily: FONT.display, fontSize: 10, letterSpacing: '0.15em',
                    color: isPulsing ? COLOR.ink0 : (isHero ? COLOR.red : COLOR.text),
                    textAlign: 'center',
                  }}>{b}</div>
                );
              })}
            </div>
            <div style={{
              alignSelf: 'center', width: 64, height: 64, borderRadius: '50%', background: COLOR.red,
              boxShadow: `0 0 24px ${COLOR.redGlow}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontFamily: FONT.display, fontSize: 22, color: 'white',
            }}>●</div>
          </div>
        </div>
      </div>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 7 · MEMORY + MCP (14.08s) ──────────
 *  Left: memory cards (contacts, projects, facts). Right: MCP host logos. */
const MemoryScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  const memCards = [
    { kind: 'CONTACT',  primary: 'Sarah Mitchell',   secondary: 'Press office · sarah@example.press · last seen 3 days ago', at: 30 },
    { kind: 'PROJECT',  primary: 'Vulcan AMR Pro',  secondary: 'Active · Goodwood reveal scheduled · 14 hero shots',  at: 70 },
    { kind: 'FACT',     primary: 'The FOM look',    secondary: 'Warm bias, mid sat, medium contrast, balanced exposure', at: 110 },
    { kind: 'CONVERSATION', primary: '"Last week\'s Vulcan brief"', secondary: '3 days ago · agreed on 9:16 + 16:9 deliverables', at: 150 },
  ];
  return (
    <AbsoluteFill style={{ padding: '160px 80px 120px', display: 'flex', gap: 60 }}>
      <SceneLabel chapter="05 · PERSISTENT MEMORY + MCP" title="Knows your studio" opacity={e(f, [0, 18], [0, 1])} />

      {/* LEFT: memory cards */}
      <div style={{ flex: 1, marginTop: 100, display: 'flex', flexDirection: 'column', gap: 14 }}>
        {memCards.map((c) => {
          const opacity = e(f, [c.at, c.at + 24], [0, 1]);
          const x = e(f, [c.at, c.at + 24], [-30, 0]);
          return (
            <div key={c.kind} style={{
              opacity, transform: `translateX(${x}px)`,
              padding: '14px 20px',
              background: COLOR.ink1,
              border: `1px solid ${COLOR.red}`,
              clipPath: BLADE_CLIP,
              display: 'flex', flexDirection: 'column', gap: 4,
            }}>
              <div style={{ fontFamily: FONT.display, fontSize: 11, letterSpacing: '0.4em', color: COLOR.red }}>{c.kind}</div>
              <div style={{ fontFamily: FONT.body, fontSize: 22, color: COLOR.text, fontWeight: 500 }}>{c.primary}</div>
              <div style={{ fontFamily: FONT.body, fontSize: 14, color: COLOR.textDim }}>{c.secondary}</div>
            </div>
          );
        })}
      </div>

      {/* RIGHT: MCP host logos as a styled grid */}
      <div style={{ width: 480, marginTop: 100, display: 'flex', flexDirection: 'column', gap: 14 }}>
        <div style={{
          fontFamily: FONT.display, fontSize: 16, letterSpacing: '0.3em', color: COLOR.red,
          opacity: e(f, [240, 270], [0, 1]),
        }}>MCP HOSTS</div>
        <div style={{
          fontFamily: FONT.body, fontSize: 14, color: COLOR.textDim,
          opacity: e(f, [240, 270], [0, 1]),
        }}>Drive the same kiosk from any host:</div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginTop: 8 }}>
          {['CLAUDE DESKTOP', 'CLAUDE CODE', 'CURSOR', 'CONTINUE'].map((h, i) => {
            const at = 270 + i * 18;
            const opacity = e(f, [at, at + 18], [0, 1]);
            return (
              <div key={h} style={{
                opacity,
                padding: '20px 16px',
                background: COLOR.ink2,
                border: `1px solid ${COLOR.line}`,
                clipPath: BLADE_CLIP,
                fontFamily: FONT.display, fontSize: 16, letterSpacing: '0.15em',
                color: COLOR.text,
                textAlign: 'center',
              }}>{h}</div>
            );
          })}
        </div>
        <div style={{
          marginTop: 12, fontFamily: FONT.mono, fontSize: 12, color: COLOR.textDim,
          opacity: e(f, [350, 380], [0, 1]),
          padding: '10px 14px', background: COLOR.ink2, border: `1px solid ${COLOR.line}`,
        }}>"url": "http://localhost:8766/mcp"</div>
      </div>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 8 · INSTALL TERMINAL (14.98s) ──────────
 *  Five terminal frames cycling, each showing the actual command + output. The
 *  cycle gives the viewer a clear "step 1, step 2, step 3" flow that mirrors
 *  the install.sh + setup-wizard.mjs experience. */
const InstallScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  /* Six steps over 450 frames = ~75 frames each. Each step has its content
   * appear via a typewriter effect. */
  const stepsConfig = [
    {
      title: 'STEP 1 · CLONE',
      command: '$ git clone https://github.com/flat-out-media/jarvis.git',
      output: ["Cloning into 'jarvis'…", "remote: Enumerating objects: 1842, done.", "Receiving objects: 100% (1842/1842), 14.2 MB", "✓ done"],
      from: 0, to: 80,
    },
    {
      title: 'STEP 2 · INSTALL',
      command: '$ cd jarvis && ./install.sh',
      output: ["▶ Checking dependencies…", "  ✓ ffmpeg ✓ ImageMagick ✓ exiftool ✓ Ollama", "▶ Pulling models (qwen2.5:14b, qwen2.5vl:7b, nomic-embed-text)…", "▶ Installing Whisper + Kokoro Python services…", "✓ install complete (4 min 12 s)"],
      from: 80, to: 180,
    },
    {
      title: 'STEP 3 · SETUP WIZARD',
      command: '$ node tools/setup-wizard.mjs',
      output: ["  ── SETUP WIZARD ──", "▶ Agent identity", "  Agent name [Flat-Out]:", "  Wake phrase [hey flat-out]:", "  Voice [bm_daniel]:"],
      from: 180, to: 260,
    },
    {
      title: 'STEP 4 · TIER + FOLDERS',
      command: '',
      output: ["▶ Hardware tier", "  m5-max — 32b/32b (production target, press-release grade)", "  ✓ Tier: m5-max", "▶ Folders", "  Shoots root [shoots]: /Volumes/Workdrive/Shoots", "  Output root [output]: /Volumes/Workdrive/Output", "  ✓ Wrote .env (12 entries) + config/brand.json"],
      from: 260, to: 360,
    },
    {
      title: 'STEP 5 · LAUNCH',
      command: '$ ./launch.sh kiosk',
      output: ["[bridge] FAL_KEY: loaded ✓", "[bridge] Ollama: http://localhost:11434 (qwen2.5:32b)", "[bridge] listening on ws://localhost:8766", "[warmup] text model \"qwen2.5:32b\" ready in 1840ms", "[warmup] Kokoro ready in 312ms", "✓ Flat-Out is live."],
      from: 360, to: duration,
    },
  ];
  /* Find current step. */
  const currentStep = stepsConfig.find(s => f >= s.from && f < s.to) || stepsConfig[stepsConfig.length - 1];
  const progress = Math.min(1, (f - currentStep.from) / Math.max(1, currentStep.to - currentStep.from - 12));
  const cmdChars = Math.floor(progress * (currentStep.command?.length || 0) * 1.6);
  /* Output lines reveal one at a time as progress advances past their thresholds. */
  const visibleOutputLines = currentStep.output.slice(0, Math.max(0, Math.floor(progress * currentStep.output.length * 1.4)));

  return (
    <AbsoluteFill style={{ padding: '110px 80px 120px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 24 }}>
      <SceneLabel chapter="06 · INSTALLATION" title="A coffee, then live" opacity={e(f, [0, 18], [0, 1])} />

      {/* Step indicator */}
      <div style={{ display: 'flex', gap: 10, marginTop: 40 }}>
        {stepsConfig.map((s, i) => {
          const isActive = f >= s.from && f < s.to;
          const isDone = f >= s.to;
          return (
            <div key={i} style={{
              padding: '6px 14px',
              fontFamily: FONT.display, fontSize: 12, letterSpacing: '0.3em',
              color: isActive ? COLOR.red : isDone ? COLOR.green : COLOR.textMuted,
              border: `1px solid ${isActive ? COLOR.red : isDone ? COLOR.green : COLOR.line}`,
              background: isActive ? COLOR.ink1 : 'transparent',
              clipPath: BLADE_CLIP,
            }}>STEP {i + 1}</div>
          );
        })}
      </div>

      <div style={{
        fontFamily: FONT.display, fontSize: 22, letterSpacing: '0.2em', color: COLOR.text,
      }}>{currentStep.title}</div>

      <TerminalFrame title="antony@m5max — bash — flat-out install" width={1280} height={460}>
        {currentStep.command && (
          <div style={{ color: '#5dd1a3' }}>{currentStep.command.slice(0, cmdChars)}<span style={{ color: COLOR.green }}>{cmdChars < currentStep.command.length ? '▍' : ''}</span></div>
        )}
        {visibleOutputLines.map((line, i) => (
          <div key={i} style={{
            color: line.startsWith('✓') ? COLOR.green :
                   line.startsWith('▶') ? '#7ab8ff' :
                   line.startsWith('  ✓') ? COLOR.green :
                   '#e6e6e6',
            marginTop: 4,
          }}>{line}</div>
        ))}
      </TerminalFrame>
    </AbsoluteFill>
  );
};

/* ────────── SCENE 9 · OUTRO (4.91s) ──────────
 *  FOM blade + tagline, slow zoom + brand red flash on the closer. */
const OutroScene: React.FC<{ duration: number }> = ({ duration }) => {
  const f = useCurrentFrame();
  const opacity = e(f, [0, 18], [0, 1]);
  /* Subtle slow scale-in over the whole scene to give the closer some weight. */
  const scale = interpolate(f, [0, duration], [1.0, 1.06], { extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic) });
  /* Brand-red flash on the last second so the viewer's last frame is the brand. */
  const flashOpacity = e(f, [duration - 30, duration - 10, duration], [0, 0.6, 0]);
  return (
    <AbsoluteFill style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', gap: 28 }}>
      <div style={{ opacity, transform: `scale(${scale})`, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 28 }}>
        <BladeMark size={150} />
        <Wordmark scale={1.2} tagline />
        <div style={{
          marginTop: 24,
          fontFamily: FONT.display, fontWeight: 500, fontSize: 18, letterSpacing: '0.5em', color: COLOR.red, textTransform: 'uppercase',
        }}>READY WHEN YOU ARE</div>
      </div>
      {/* Brand-red flash overlay at scene end. */}
      <div style={{
        position: 'absolute', inset: 0, background: COLOR.red, opacity: flashOpacity, pointerEvents: 'none',
      }} />
    </AbsoluteFill>
  );
};

/* ────────── SCENE REGISTRY ──────────
 *  Maps scene id → component. SceneRouter dispatches via this lookup so adding
 *  / removing a scene is a registry edit + a manifest entry, no rewiring. */
const SCENE_COMPONENTS: Record<SceneId, React.FC<{ duration: number }>> = {
  title:   TitleScene,
  hook:    HookScene,
  voice:   VoiceScene,
  vision:  VisionScene,
  edit:    EditScene,
  brand:   BrandScene,
  memory:  MemoryScene,
  install: InstallScene,
  outro:   OutroScene,
};
